PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix isa:   <http://onto.toxbank.net/isa/>
prefix dcterms: <http://purl.org/dc/terms/>

SELECT * WHERE {
 ?investigation rdf:type isa:Investigation.
 ?investigation isa:hasStudy ?study.
 ?study rdf:type isa:Study.
 ?study dcterms:title ?studytitle.
 ?study isa:hasAssay ?assay.
 ?assay rdf:type  isa:Assay.
 ?assay isa:hasEndpoint ?endpoint.
 ?assay isa:usesTechnology ?technology.
} 