#Investigation service query
#Retrieves investigation URI and factors (name, value, ontology URI of the value)
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix isa:   <http://onto.toxbank.net/isa/>
prefix dcterms: <http://purl.org/dc/terms/>

SELECT distinct ?inv ?factorname ?value ?ontouri WHERE {
 ?inv rdf:type isa:Investigation.
 ?inv isa:hasStudy ?study.
 ?node isa:hasStudy ?study.
 ?node rdf:type isa:MaterialNode.
 ?node isa:hasMaterial ?sample.
 ?sample isa:hasFactorValue ?factorValue.
 ?factorValue isa:hasOntologyTerm  ?ontouri.
 ?factorValue isa:hasValue  ?value.
 ?factorValue isa:hasFactor ?factor. 
 ?factor dcterms:title ?factorname.
} order by ?inv