#Investigation service query
#Retrieves investigation URI and characteristics (name, value, ontology URI of the value)
#
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix isa:   <http://onto.toxbank.net/isa/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix tb:    <http://onto.toxbank.net/api/> 


SELECT distinct ?inv ?propname ?propvalue ?ontouri WHERE {
 ?inv rdf:type isa:Investigation.
 ?inv isa:hasStudy ?study.
 ?node isa:hasStudy ?study.
 ?node rdf:type isa:MaterialNode.
 ?node isa:hasMaterial ?sample.
 ?sample isa:hasCharacteristicValue ?propValue.
 ?propValue isa:hasOntologyTerm ?ontouri . 
 ?propValue isa:hasValue  ?value.
 ?propValue isa:hasProperty ?property. 
 ?property dcterms:title ?propname.
} order by ?inv