#Investigation service query
#Retrieves investigation and protocol URIs
#

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix isa:   <http://onto.toxbank.net/isa/>
prefix dcterms: <http://purl.org/dc/terms/>
prefix tb:    <http://onto.toxbank.net/api/> 

SELECT distinct ?inv ?protocol ?label WHERE {
 ?inv rdf:type isa:Investigation.
 ?inv isa:hasStudy ?study.
 ?study isa:hasProtocol ?protocol.
 OPTIONAL {
 ?protocol rdfs:label ?label.
 }
}