#Investigation service query
#Retrieves investigation and protocol URIs
#

PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX isa:   <http://onto.toxbank.net/isa/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX tb:    <http://onto.toxbank.net/api/> 

SELECT DISTINCT ?investigation ?protocol ?label WHERE {
 ?investigation rdf:type isa:Investigation.
 ?investigation isa:hasStudy ?study.
 ?investigation tb:isPublished "true"^^<http://www.w3.org/2001/XMLSchema#boolean>.
 ?investigation tb:isSummarySearchable "true"^^<http://www.w3.org/2001/XMLSchema#boolean>.
 ?study isa:hasProtocol ?protocol.
 OPTIONAL {
 ?protocol rdfs:label ?label.
 }
}
