PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX isa:   <http://onto.toxbank.net/isa/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?study ?studytitle ?assay ?assay ?endpoint ?technology WHERE {
 <%{investigation_uri}> isa:hasStudy ?study.
 ?study rdf:type isa:Study.
 ?study dcterms:title ?studytitle.
 ?study isa:hasAssay ?assay.
 ?assay rdf:type  isa:Assay.
 ?assay isa:hasEndpoint ?endpoint.
 ?assay isa:usesTechnology ?technology.
} 