PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX isa:   <http://onto.toxbank.net/isa/>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?study ?protocol ?assay ?endpoint ?endpointLabel ?technology ?technologyLabel WHERE {
 <%{investigation_uri}> isa:hasStudy ?study.
 ?study rdf:type isa:Study;
      dcterms:title ?studytitle;
      isa:hasProtocol ?protocol;
      isa:hasAssay ?assay.
  OPTIONAL {
     ?assay isa:hasEndpoint ?endpoint.
     ?endpoint rdfs:label ?endpointLabel.
  }.
  OPTIONAL {
     ?assay isa:usesTechnology ?technology.
     ?technology rdfs:label ?technologyLabel.
  }.   
} 